<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PersonalMediaManager.Server</RootNamespace>
    <AssemblyName>PersonalMediaManager.Server</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../PersonalMediaManager.Host/PersonalMediaManager.Host.csproj" />
  </ItemGroup>
</Project>
